version: '3.5'

services:
  postgres:
    env_file:
      - "src/.env"
    restart: always
    container_name: postgres_db_app
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /postgres/data/
    ports:
      - "5433:5432"
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin_fastapi
    restart: always
    env_file:
      - "src/.env"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
        - "5050:80"
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge