version: '3.5'

services:
  postgres:
    env_file:
      - ".env"
    restart: always
    network_mode: "host"
    container_name: postgres_db_app
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /postgres/data/
      POSTGRES_INITDB_ARGS: "-A md5"

    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
        - "5050:80"
    depends_on:
      - postgres